import { imageData } from "./assets/imageData";

export const data = {
  slider: [
    {
      collection: "SUMMER 2020",
      title: "NEW COLLECTION",
      description:
        "We know how large objects will act,but things on a small scale.",
      button: "SHOP NOW",
      image: imageData.slider[0],
    },
    {
      title: "BLACK FRIDAY",
      description:
        "We know how large objects will act, but things on a small scale just do not act that way.",
      button: "START NOW",
      image: imageData.slider[1],
    },
  ],
  categories: [
    {
      name: "MEN",
      image: imageData.categories[0],
    },
    {
      name: "WOMAN",
      image: imageData.categories[1],
    },
    {
      name: "ACCESSORIES",
      image: imageData.categories[2],
    },
    {
      name: "KIDS",
      image: imageData.categories[3],
    },
  ],
  bestsellers: [
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[0],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[1],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[2],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[3],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[4],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[5],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[6],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.bestsellers[7],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
  ],
  sliderProduct: [
    {
      collection: "SUMMER 2020",
      title: "Vita Classic Product",
      description:
        "We know how large objects will act, We know how are objects will act, We know",
      price: "$16.48",
      button: "ADD TO CART",
      image: imageData.sliderproduct,
    },
  ],
  featuredPosts: [
    {
      title: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2021",
      comment: 10,
      image: imageData.featured[0],
    },
    {
      title: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2021",
      comment: 10,
      image: imageData.featured[1],
    },
    {
      title: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2021",
      comment: 10,
      image: imageData.featured[2],
    },
  ],
  productcategories: [
    {
      title: "CLOTHS",
      items: "5 Items",
      image: imageData.productcategories[0],
    },
    {
      title: "CLOTHS",
      items: "5 Items",
      image: imageData.productcategories[1],
    },
    {
      title: "CLOTHS",
      items: "5 Items",
      image: imageData.productcategories[2],
    },
    {
      title: "CLOTHS",
      items: "5 Items",
      image: imageData.productcategories[3],
    },
    {
      title: "CLOTHS",
      items: "5 Items",
      image: imageData.productcategories[4],
    },
  ],
  productListOption: [
    "Popularity",
    "Most Reviewed",
    "Cheapest",
    "The Most expensive",
  ],
  productListDetail: [
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[0],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[1],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[2],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[3],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[4],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[5],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[6],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[7],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[8],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[9],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[10],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
    {
      name: "Graphic Design",
      description: "English Department",
      price: "$16.48",
      discountPrice: "$6.48",
      image: imageData.productListDetail[11],
      colors: [
        "w-4 h-4 bg-sky-500 rounded-full",
        "w-4 h-4 bg-teal-700 rounded-full",
        "w-4 h-4 bg-orange-400 rounded-full",
        "w-4 h-4 bg-slate-800 rounded-full",
      ],
    },
  ],
};
